// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: mao.proto

package api

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GPS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *GPS) Reset() {
	*x = GPS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPS) ProtoMessage() {}

func (x *GPS) ProtoReflect() protoreflect.Message {
	mi := &file_mao_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPS.ProtoReflect.Descriptor instead.
func (*GPS) Descriptor() ([]byte, []int) {
	return file_mao_proto_rawDescGZIP(), []int{0}
}

func (x *GPS) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPS) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type MaoRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RStr string `protobuf:"bytes,1,opt,name=rStr,proto3" json:"rStr,omitempty"`
}

func (x *MaoRequestData) Reset() {
	*x = MaoRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaoRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaoRequestData) ProtoMessage() {}

func (x *MaoRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_mao_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaoRequestData.ProtoReflect.Descriptor instead.
func (*MaoRequestData) Descriptor() ([]byte, []int) {
	return file_mao_proto_rawDescGZIP(), []int{1}
}

func (x *MaoRequestData) GetRStr() string {
	if x != nil {
		return x.RStr
	}
	return ""
}

type MaoResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Location *GPS   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *MaoResponseData) Reset() {
	*x = MaoResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaoResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaoResponseData) ProtoMessage() {}

func (x *MaoResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_mao_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaoResponseData.ProtoReflect.Descriptor instead.
func (*MaoResponseData) Descriptor() ([]byte, []int) {
	return file_mao_proto_rawDescGZIP(), []int{2}
}

func (x *MaoResponseData) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MaoResponseData) GetLocation() *GPS {
	if x != nil {
		return x.Location
	}
	return nil
}

type MaoStreamDataA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocPeer_A *GPS `protobuf:"bytes,1,opt,name=loc_peer_A,json=locPeerA,proto3" json:"loc_peer_A,omitempty"`
}

func (x *MaoStreamDataA) Reset() {
	*x = MaoStreamDataA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaoStreamDataA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaoStreamDataA) ProtoMessage() {}

func (x *MaoStreamDataA) ProtoReflect() protoreflect.Message {
	mi := &file_mao_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaoStreamDataA.ProtoReflect.Descriptor instead.
func (*MaoStreamDataA) Descriptor() ([]byte, []int) {
	return file_mao_proto_rawDescGZIP(), []int{3}
}

func (x *MaoStreamDataA) GetLocPeer_A() *GPS {
	if x != nil {
		return x.LocPeer_A
	}
	return nil
}

type MaoStreamDataB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocPeer_B *GPS `protobuf:"bytes,1,opt,name=loc_peer_B,json=locPeerB,proto3" json:"loc_peer_B,omitempty"`
}

func (x *MaoStreamDataB) Reset() {
	*x = MaoStreamDataB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaoStreamDataB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaoStreamDataB) ProtoMessage() {}

func (x *MaoStreamDataB) ProtoReflect() protoreflect.Message {
	mi := &file_mao_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaoStreamDataB.ProtoReflect.Descriptor instead.
func (*MaoStreamDataB) Descriptor() ([]byte, []int) {
	return file_mao_proto_rawDescGZIP(), []int{4}
}

func (x *MaoStreamDataB) GetLocPeer_B() *GPS {
	if x != nil {
		return x.LocPeer_B
	}
	return nil
}

var File_mao_proto protoreflect.FileDescriptor

var file_mao_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x61, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x3f, 0x0a, 0x03, 0x47, 0x50, 0x53, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x4d, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x72, 0x53, 0x74, 0x72, 0x22, 0x4e, 0x0a, 0x0f, 0x4d, 0x61, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x50, 0x53, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x39, 0x0a, 0x0e, 0x4d, 0x61, 0x6f, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x41, 0x12, 0x27, 0x0a, 0x0a, 0x6c, 0x6f,
	0x63, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x41, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x50, 0x53, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x50, 0x65,
	0x65, 0x72, 0x41, 0x22, 0x39, 0x0a, 0x0e, 0x4d, 0x61, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x12, 0x27, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x5f, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x42, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x47, 0x50, 0x53, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x50, 0x65, 0x65, 0x72, 0x42, 0x32, 0x49,
	0x0a, 0x06, 0x42, 0x69, 0x67, 0x6d, 0x61, 0x6f, 0x12, 0x3f, 0x0a, 0x0e, 0x51, 0x69, 0x6e, 0x67,
	0x64, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x4d, 0x61, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x61, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6d, 0x61, 0x6f, 0x6a, 0x69, 0x61, 0x6e, 0x77, 0x65, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mao_proto_rawDescOnce sync.Once
	file_mao_proto_rawDescData = file_mao_proto_rawDesc
)

func file_mao_proto_rawDescGZIP() []byte {
	file_mao_proto_rawDescOnce.Do(func() {
		file_mao_proto_rawDescData = protoimpl.X.CompressGZIP(file_mao_proto_rawDescData)
	})
	return file_mao_proto_rawDescData
}

var file_mao_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mao_proto_goTypes = []interface{}{
	(*GPS)(nil),             // 0: main.GPS
	(*MaoRequestData)(nil),  // 1: main.MaoRequestData
	(*MaoResponseData)(nil), // 2: main.MaoResponseData
	(*MaoStreamDataA)(nil),  // 3: main.MaoStreamDataA
	(*MaoStreamDataB)(nil),  // 4: main.MaoStreamDataB
}
var file_mao_proto_depIdxs = []int32{
	0, // 0: main.MaoResponseData.location:type_name -> main.GPS
	0, // 1: main.MaoStreamDataA.loc_peer_A:type_name -> main.GPS
	0, // 2: main.MaoStreamDataB.loc_peer_B:type_name -> main.GPS
	1, // 3: main.Bigmao.QingdaoRequest:input_type -> main.MaoRequestData
	2, // 4: main.Bigmao.QingdaoRequest:output_type -> main.MaoResponseData
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mao_proto_init() }
func file_mao_proto_init() {
	if File_mao_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mao_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaoRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaoResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaoStreamDataA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaoStreamDataB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mao_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mao_proto_goTypes,
		DependencyIndexes: file_mao_proto_depIdxs,
		MessageInfos:      file_mao_proto_msgTypes,
	}.Build()
	File_mao_proto = out.File
	file_mao_proto_rawDesc = nil
	file_mao_proto_goTypes = nil
	file_mao_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BigmaoClient is the client API for Bigmao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BigmaoClient interface {
	QingdaoRequest(ctx context.Context, in *MaoRequestData, opts ...grpc.CallOption) (*MaoResponseData, error)
}

type bigmaoClient struct {
	cc grpc.ClientConnInterface
}

func NewBigmaoClient(cc grpc.ClientConnInterface) BigmaoClient {
	return &bigmaoClient{cc}
}

func (c *bigmaoClient) QingdaoRequest(ctx context.Context, in *MaoRequestData, opts ...grpc.CallOption) (*MaoResponseData, error) {
	out := new(MaoResponseData)
	err := c.cc.Invoke(ctx, "/main.Bigmao/QingdaoRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BigmaoServer is the server API for Bigmao service.
type BigmaoServer interface {
	QingdaoRequest(context.Context, *MaoRequestData) (*MaoResponseData, error)
}

// UnimplementedBigmaoServer can be embedded to have forward compatible implementations.
type UnimplementedBigmaoServer struct {
}

func (*UnimplementedBigmaoServer) QingdaoRequest(context.Context, *MaoRequestData) (*MaoResponseData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QingdaoRequest not implemented")
}

func RegisterBigmaoServer(s *grpc.Server, srv BigmaoServer) {
	s.RegisterService(&_Bigmao_serviceDesc, srv)
}

func _Bigmao_QingdaoRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaoRequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BigmaoServer).QingdaoRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Bigmao/QingdaoRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BigmaoServer).QingdaoRequest(ctx, req.(*MaoRequestData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bigmao_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Bigmao",
	HandlerType: (*BigmaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QingdaoRequest",
			Handler:    _Bigmao_QingdaoRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mao.proto",
}
